### ISSUE TITLE
Running example_completion.py with CodeLLama-34b locally returns an assertion error.

### ISSUE THREAD

**Issue by stephenwithav** [meta-llama/codellama#165]
```
torchrun --nproc_per_node 1 example_completion.py     --ckpt_dir CodeLlama-34b/     --tokenizer_path CodeLlama-34b/tokenizer.model     --max_seq_len 128 --max_batch_size 4 --nodes 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "example_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/home/steven/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/steven/.local/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/steven/.local/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_completion.py", line 20, in main
    generator = Llama.build(
  File "/home/steven/github/stephenwithav/codellama/llama/generation.py", line 97, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=4 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2308980) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/steven/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/steven/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/steven/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/steven/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/steven/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/steven/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-15_15:48:25
  host      : work
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2308980)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by humza-sami** [comment]
What is your system specs ?

**Comment by stephenwithav** [comment]
12 i7 cores, 64GB RAM.

**Comment by humza-sami** [comment]
Can you share code how you are running the code ?
Also nvidia-smi output as well

**Comment by stephenwithav** [comment]
I reinstalled 7b-Instruct, 13b-Instruct, and 13b today and everything worked fine.  I must have made an error previously.  Thanks for your assistance!
