### ISSUE TITLE
Can't run any inference

### ISSUE THREAD

**Issue by Entretoize** [meta-llama/codellama#50]
I'm trying to use the exemple inference on windows 10 with python 10, like that:

`(py310) d:\git\codellama>torchrun --nproc_per_node 1 example_instructions.py --ckpt_dir CodeLlama-7b-Instruct/ --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model --max_seq_len 512 --max_batch_size 4`

But it seems trying to connect to something in docker that I'm not using. That may be related to NCCL even if I only have one gpu... I don't understand.
This is the output I get:

```
NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - LÆadresse demandÚe nÆest pas valide dans son contexte.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - LÆadresse demandÚe nÆest pas valide dans son contexte.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - LÆadresse demandÚe nÆest pas valide dans son contexte.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - LÆadresse demandÚe nÆest pas valide dans son contexte.).
Traceback (most recent call last):
  File "d:\git\codellama\example_instructions.py", line 68, in <module>
    fire.Fire(main)
  File "D:\anaconda3\envs\py310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\anaconda3\envs\py310\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\anaconda3\envs\py310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "d:\git\codellama\example_instructions.py", line 20, in main
    generator = Llama.build(
  File "d:\git\codellama\llama\generation.py", line 68, in build
    torch.distributed.init_process_group("nccl")
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13132) of binary: D:\anaconda3\envs\py310\python.exe
Traceback (most recent call last):
  File "D:\anaconda3\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\py310\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\anaconda3\envs\py310\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_instructions.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-28_09:51:06
  host      : DESKTOP-123456
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13132)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by loleg** [comment]
I'm getting this as well, on Linux. Would be nice to have a `USE_NCCL=0` or such environmental variable. One workaround is to swap it out and replace with GLOO. See example in my branch here: https://github.com/loleg/codellama/blob/without-nccl/llama/generation.py#L68 (not working yet, throwing `ChildFailedError` after processing for a while)

See also #40

**Comment by Entretoize** [comment]
That works, thank you !
