### ISSUE TITLE
Invalid load key error

### ISSUE THREAD

**Issue by junuMoon** [meta-llama/codellama#59]
Cmd line:
`torchrun --nproc_per_node 1 example_infilling.py --ckpt_dir CodeLlama-7b-Instruct/ --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model --max_seq_len 512 -- max_batch_size 4`

Error Raised
```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/fran/codellama/example_infilling.py", line 79, in <module>
    fire.Fire(main)
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/fran/codellama/example_infilling.py", line 18, in main
    generator = Llama.build(
  File "/home/fran/codellama/llama/generation.py", line 90, in build
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 463834) of binary: /home/fran/miniconda3/envs/cs-gpt/bin/python
Traceback (most recent call last):
  File "/home/fran/miniconda3/envs/cs-gpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/fran/miniconda3/envs/cs-gpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_infilling.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-29_20:39:20
  host      : fran.rtzr.ai
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 463834)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by mhamra** [comment]
I reported a similar problem here: #55

**Comment by GaganHonor** [comment]
The error message you are getting is:

```
_pickle.UnpicklingError: invalid load key, '<'.
```

This means that the `torch.load()` function was unable to load the checkpoint file. The `<` character is not a valid load key.

The most likely reason for this error is that the checkpoint file is corrupt. You can try to verify the integrity of the checkpoint file by running the following command:

```
sha256sum CodeLlama-7b-Instruct.ckpt
```

If the checksum of the checkpoint file does not match the checksum that is provided in the CodeLlama documentation, then the checkpoint file is corrupt.

If the checkpoint file is not corrupt, then the problem might be with the `torch.load()` function. You can try to update the `torch` library to the latest version.

Here are some additional things you can try:

* Make sure that you are using the correct version of Python. The `torch.load()` function requires Python version 3.6 or higher.
* Make sure that the checkpoint file is in the same location as the `example_infilling.py` file.
* Try running the `torch.load()` function with the `allow_pickle=False` argument. This will prevent the `torch.load()` function from trying to load the checkpoint file as a pickle file.

(❁´◡`❁) Helpful ? Y / N : ASK MOREEEEEE
![CommitPoliceCommitGIF](https://github.com/facebookresearch/codellama/assets/141204441/399c677a-5053-43b4-bdc0-dc0d65658185)
