### ISSUE TITLE
Running 7B model on RTX 4070 (12GB) causes "out of memory" error

### ISSUE THREAD

**Issue by zono** [meta-llama/codellama#82]
Running example_completion.py with a 7B model on an RTX 4070 (12GB VRAM) results in an "out of memory" error.

Is it possible to run example_completion.py without having to purchase a higher-spec GPU than the RTX 4070?

* GPU Info (before running example_completion.py)

```
# nvidia-smi
Sun Sep  3 13:32:02 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070        Off | 00000000:01:00.0  On |                  N/A |
|  0%   47C    P2              32W / 200W |    697MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

* Command and Error

```
# torchrun --nproc_per_node 1 example_completion.py --ckpt_dir CodeLlama-7b/ --tokenizer_path CodeLlama-7b/tokenizer.model --max_seq_len 128 --max_batch_size 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/root/codellama/example_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/codellama/example_completion.py", line 20, in main
    generator = Llama.build(
  File "/root/codellama/llama/generation.py", line 105, in build
    model = Transformer(model_args)
  File "/root/codellama/llama/model.py", line 260, in __init__
    self.layers.append(TransformerBlock(layer_id, params))
  File "/root/codellama/llama/model.py", line 222, in __init__
    self.attention = Attention(args)
  File "/root/codellama/llama/model.py", line 100, in __init__
    self.wq = ColumnParallelLinear(
  File "/usr/local/lib/python3.10/dist-packages/fairscale/nn/model_parallel/layers.py", line 262, in __init__
    self.weight = Parameter(torch.Tensor(self.output_size_per_partition, self.in_features))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 11.69 GiB total capacity; 10.85 GiB already allocated; 28.25 MiB free; 10.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4749) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-03_13:25:53
  host      : daiv
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4749)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

* Git revision

```
# git rev-parse HEAD
e064c1c24c377cc0875711440ef4c0a6eaf0147b
```

* OS

```
# lsb_release -a
Description:	Ubuntu 22.04.3 LTS
```

**Comment by zono** [comment]
It seems like quantization will make it executable. I'm currently testing it

**Comment by Romainsauvestre** [comment]
> It seems like quantization will make it executable. I'm currently testing it

@zono did you manage to make it work?
You can have a look at this [blog post](https://towardsdatascience.com/quantize-llama-models-with-ggml-and-llama-cpp-3612dfbcc172) and [repo](https://github.com/ggerganov/llama.cpp) for pointers.

**Comment by LinJia21** [comment]
3070 can run 7B model

**Comment by RiccardoBarbieri** [comment]
> 3070 can run 7B model

I am currently trying to run the 7B model with my 3070 but I get a CUDA OutOfMemoryError, tried reducing batch size but I still get the error

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 7.78 GiB of which 61.00 MiB is free. Including non-PyTorch memory, this process has 7.39 GiB memory in use. Of the allocated memory 7.21 GiB is allocated by PyTorch, and 5.22 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by shaunakjoshi12** [comment]
@zono and @RiccardoBarbieri were you able to run successfully on a GPU with 12GB mem? Cos I am facing the same thing. Mine is GTX 1080 ti
