### ISSUE TITLE
Unable to run example_complete.py on windows 10

### ISSUE THREAD

**Issue by yxprojectdocs** [meta-llama/codellama#93]
I tried running the example code given but theres an EOFerror, out of input that keeps popping up. Anyways to solve it?

torchrun --nproc_per_node 1 example_completion.py --ckpt_dir CodeLlama-7b --tokenizer_path CodeLlama-7b/tokenizer.model --max_seq_len 128 --max_batch_size 4
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/yx/codellama/example_completion.py", line 55, in <module>
    fire.Fire(main)
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/yx/codellama/example_completion.py", line 20, in main
    generator = Llama.build(
  File "/home/yx/codellama/llama/generation.py", line 90, in build
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 94531) of binary: /home/yx/codellama/.conda/bin/python
Traceback (most recent call last):
  File "/home/yx/codellama/.conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yx/codellama/.conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-05_17:06:02
  host      : DESKTOP-860T855.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 94531)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by moonman239** [comment]
I seem to be having a similar issue. I cloned the repository, downloaded the model, ran the setup instructions, then ran the following command, all in a WSL environment running Ubuntu:

```
torchrun --nproc_per_node 1 example_instructions.py \
>     --ckpt_dir CodeLlama-7b-Instruct/ \
 --tokenizer_path CodeLlama-7b-Instruct/tokenizer.mo>     --tokenizer_path CodeLlama-7b-Instruct/tokenizer.model \
>     --max_seq_len 512 --max_batch_size 4
```

and got this output:

```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/home/moonman239/.local/lib/python3.10/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
Traceback (most recent call last):
  File "/mnt/c/Users/moonman239/codellama/example_instructions.py", line 68, in <module>
    fire.Fire(main)
  File "/home/moonman239/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/moonman239/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/moonman239/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/c/Users/moonman239/codellama/example_instructions.py", line 20, in main
    generator = Llama.build(
  File "/mnt/c/Users/moonman239/codellama/llama/generation.py", line 120, in build
    model = Transformer(model_args)
  File "/mnt/c/Users/moonman239/codellama/llama/model.py", line 270, in __init__
    self.layers.append(TransformerBlock(layer_id, params))
  File "/mnt/c/Users/moonman239/codellama/llama/model.py", line 232, in __init__
    self.attention = Attention(args)
  File "/mnt/c/Users/moonman239/codellama/llama/model.py", line 131, in __init__
    self.wo = RowParallelLinear(
  File "/home/moonman239/.local/lib/python3.10/site-packages/fairscale/nn/model_parallel/layers.py", line 349, in __init__
    self.weight = Parameter(torch.Tensor(self.out_features, self.input_size_per_partition))
RuntimeError: r.cuMemAddressReserve_ INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":22, please report a bug to PyTorch.
[2023-11-13 13:45:52,497] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 247714) of binary: /usr/local/bin/python3
Traceback (most recent call last):
  File "/home/moonman239/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/moonman239/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/moonman239/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/moonman239/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/moonman239/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/moonman239/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_instructions.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-13_13:45:52
  host      : DESKTOP-7BUAAQB.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 247714)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by FuncAccount** [comment]
I got similar issue, ran in windows 11 environment and got this error
E:\ML_Project\LLaMa2\codellama>torchrun --nproc_per_node 1 example_completion.py --ckpt_dir CodeLlama-7b/ --tokenizer_path CodeLlama-7b/tokenizer.model --max_seq_len 128 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-UDLTJ95]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-UDLTJ95]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-UDLTJ95]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-UDLTJ95]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "E:\ML_Project\LLaMa2\codellama\example_completion.py", line 55, in <module>
    fire.Fire(main)
  File "C:\Users\Yijie\AppData\Roaming\Python\Python310\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Yijie\AppData\Roaming\Python\Python310\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Yijie\AppData\Roaming\Python\Python310\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\ML_Project\LLaMa2\codellama\example_completion.py", line 20, in main
    generator = Llama.build(
  File "E:\ML_Project\LLaMa2\codellama\llama\generation.py", line 76, in build
    torch.distributed.init_process_group("nccl")
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26072) of binary: C:\Users\Yijie\AppData\Local\Programs\Python\Python310\python.exe
Traceback (most recent call last):
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\Yijie\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
